version: '3.8' 

volumes:
  db-store:

services:
  # php
  app: 
    container_name: sodate_php
    build: ./infra/php
    volumes:
      - ./backend:/work
  # nginx
  web:
    image: nginx:1.16-alpine
    container_name: sodate_nginx
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  # MySQL
  db:
    container_name: sodate_db
    build: ./infra/mysql
    ports:
      - 5306:3306
    volumes:
      - db-store:/var/lib/mysql
